//
// Autogenerated by Thrift Compiler (0.22.0)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//
"use strict";

var thrift = require('thrift');
var Thrift = thrift.Thrift;
var Q = thrift.Q;
var Int64 = require('node-int64');


var ttypes = module.exports = {};
var TalkException = module.exports.TalkException = function(args) {
  Thrift.TException.call(this, "TalkException");
  this.name = "TalkException";
  this.code = null;
  this.reason = null;
  if (args) {
    if (args.code !== undefined && args.code !== null) {
      this.code = args.code;
    }
    if (args.reason !== undefined && args.reason !== null) {
      this.reason = args.reason;
    }
  }
};
Thrift.inherits(TalkException, Thrift.TException);
TalkException.prototype.name = 'TalkException';
TalkException.prototype[Symbol.for("read")] = function(input) {
  input.readStructBegin();
  while (true) {
    var ret = input.readFieldBegin();
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid) {
      case 1:
      if (ftype == Thrift.Type.I32) {
        this.code = input.readI32();
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.STRING) {
        this.reason = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

TalkException.prototype[Symbol.for("write")] = function(output) {
  output.writeStructBegin('TalkException');
  if (this.code !== null && this.code !== undefined) {
    output.writeFieldBegin('code', Thrift.Type.I32, 1);
    output.writeI32(this.code);
    output.writeFieldEnd();
  }
  if (this.reason !== null && this.reason !== undefined) {
    output.writeFieldBegin('reason', Thrift.Type.STRING, 2);
    output.writeString(this.reason);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var SecondaryQrCodeException = module.exports.SecondaryQrCodeException = function(args) {
  Thrift.TException.call(this, "SecondaryQrCodeException");
  this.name = "SecondaryQrCodeException";
  this.code = null;
  this.reason = null;
  if (args) {
    if (args.code !== undefined && args.code !== null) {
      this.code = args.code;
    }
    if (args.reason !== undefined && args.reason !== null) {
      this.reason = args.reason;
    }
  }
};
Thrift.inherits(SecondaryQrCodeException, Thrift.TException);
SecondaryQrCodeException.prototype.name = 'SecondaryQrCodeException';
SecondaryQrCodeException.prototype[Symbol.for("read")] = function(input) {
  input.readStructBegin();
  while (true) {
    var ret = input.readFieldBegin();
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid) {
      case 1:
      if (ftype == Thrift.Type.I32) {
        this.code = input.readI32();
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.STRING) {
        this.reason = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

SecondaryQrCodeException.prototype[Symbol.for("write")] = function(output) {
  output.writeStructBegin('SecondaryQrCodeException');
  if (this.code !== null && this.code !== undefined) {
    output.writeFieldBegin('code', Thrift.Type.I32, 1);
    output.writeI32(this.code);
    output.writeFieldEnd();
  }
  if (this.reason !== null && this.reason !== undefined) {
    output.writeFieldBegin('reason', Thrift.Type.STRING, 2);
    output.writeString(this.reason);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var CreateSessionRequest = module.exports.CreateSessionRequest = function(args) {
  this.dummy = null;
  if (args) {
    if (args.dummy !== undefined && args.dummy !== null) {
      this.dummy = args.dummy;
    }
  }
};
CreateSessionRequest.prototype = {};
CreateSessionRequest.prototype[Symbol.for("read")] = function(input) {
  input.readStructBegin();
  while (true) {
    var ret = input.readFieldBegin();
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid) {
      case 1:
      if (ftype == Thrift.Type.STRING) {
        this.dummy = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

CreateSessionRequest.prototype[Symbol.for("write")] = function(output) {
  output.writeStructBegin('CreateSessionRequest');
  if (this.dummy !== null && this.dummy !== undefined) {
    output.writeFieldBegin('dummy', Thrift.Type.STRING, 1);
    output.writeString(this.dummy);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var CreateSessionResponse = module.exports.CreateSessionResponse = function(args) {
  this.authSessionId = null;
  if (args) {
    if (args.authSessionId !== undefined && args.authSessionId !== null) {
      this.authSessionId = args.authSessionId;
    }
  }
};
CreateSessionResponse.prototype = {};
CreateSessionResponse.prototype[Symbol.for("read")] = function(input) {
  input.readStructBegin();
  while (true) {
    var ret = input.readFieldBegin();
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid) {
      case 1:
      if (ftype == Thrift.Type.STRING) {
        this.authSessionId = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

CreateSessionResponse.prototype[Symbol.for("write")] = function(output) {
  output.writeStructBegin('CreateSessionResponse');
  if (this.authSessionId !== null && this.authSessionId !== undefined) {
    output.writeFieldBegin('authSessionId', Thrift.Type.STRING, 1);
    output.writeString(this.authSessionId);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var CreateQrCodeRequest = module.exports.CreateQrCodeRequest = function(args) {
  this.authSessionId = null;
  if (args) {
    if (args.authSessionId !== undefined && args.authSessionId !== null) {
      this.authSessionId = args.authSessionId;
    }
  }
};
CreateQrCodeRequest.prototype = {};
CreateQrCodeRequest.prototype[Symbol.for("read")] = function(input) {
  input.readStructBegin();
  while (true) {
    var ret = input.readFieldBegin();
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid) {
      case 1:
      if (ftype == Thrift.Type.STRING) {
        this.authSessionId = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

CreateQrCodeRequest.prototype[Symbol.for("write")] = function(output) {
  output.writeStructBegin('CreateQrCodeRequest');
  if (this.authSessionId !== null && this.authSessionId !== undefined) {
    output.writeFieldBegin('authSessionId', Thrift.Type.STRING, 1);
    output.writeString(this.authSessionId);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var CreateQrCodeForSecureResponse = module.exports.CreateQrCodeForSecureResponse = function(args) {
  this.callbackUrl = null;
  this.longPollingMaxCount = null;
  this.longPollingIntervalSec = null;
  this.nonce = null;
  if (args) {
    if (args.callbackUrl !== undefined && args.callbackUrl !== null) {
      this.callbackUrl = args.callbackUrl;
    }
    if (args.longPollingMaxCount !== undefined && args.longPollingMaxCount !== null) {
      this.longPollingMaxCount = args.longPollingMaxCount;
    }
    if (args.longPollingIntervalSec !== undefined && args.longPollingIntervalSec !== null) {
      this.longPollingIntervalSec = args.longPollingIntervalSec;
    }
    if (args.nonce !== undefined && args.nonce !== null) {
      this.nonce = args.nonce;
    }
  }
};
CreateQrCodeForSecureResponse.prototype = {};
CreateQrCodeForSecureResponse.prototype[Symbol.for("read")] = function(input) {
  input.readStructBegin();
  while (true) {
    var ret = input.readFieldBegin();
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid) {
      case 1:
      if (ftype == Thrift.Type.STRING) {
        this.callbackUrl = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.I32) {
        this.longPollingMaxCount = input.readI32();
      } else {
        input.skip(ftype);
      }
      break;
      case 3:
      if (ftype == Thrift.Type.I32) {
        this.longPollingIntervalSec = input.readI32();
      } else {
        input.skip(ftype);
      }
      break;
      case 4:
      if (ftype == Thrift.Type.STRING) {
        this.nonce = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

CreateQrCodeForSecureResponse.prototype[Symbol.for("write")] = function(output) {
  output.writeStructBegin('CreateQrCodeForSecureResponse');
  if (this.callbackUrl !== null && this.callbackUrl !== undefined) {
    output.writeFieldBegin('callbackUrl', Thrift.Type.STRING, 1);
    output.writeString(this.callbackUrl);
    output.writeFieldEnd();
  }
  if (this.longPollingMaxCount !== null && this.longPollingMaxCount !== undefined) {
    output.writeFieldBegin('longPollingMaxCount', Thrift.Type.I32, 2);
    output.writeI32(this.longPollingMaxCount);
    output.writeFieldEnd();
  }
  if (this.longPollingIntervalSec !== null && this.longPollingIntervalSec !== undefined) {
    output.writeFieldBegin('longPollingIntervalSec', Thrift.Type.I32, 3);
    output.writeI32(this.longPollingIntervalSec);
    output.writeFieldEnd();
  }
  if (this.nonce !== null && this.nonce !== undefined) {
    output.writeFieldBegin('nonce', Thrift.Type.STRING, 4);
    output.writeString(this.nonce);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var CheckQrCodeVerifiedRequest = module.exports.CheckQrCodeVerifiedRequest = function(args) {
  this.authSessionId = null;
  if (args) {
    if (args.authSessionId !== undefined && args.authSessionId !== null) {
      this.authSessionId = args.authSessionId;
    }
  }
};
CheckQrCodeVerifiedRequest.prototype = {};
CheckQrCodeVerifiedRequest.prototype[Symbol.for("read")] = function(input) {
  input.readStructBegin();
  while (true) {
    var ret = input.readFieldBegin();
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid) {
      case 1:
      if (ftype == Thrift.Type.STRING) {
        this.authSessionId = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

CheckQrCodeVerifiedRequest.prototype[Symbol.for("write")] = function(output) {
  output.writeStructBegin('CheckQrCodeVerifiedRequest');
  if (this.authSessionId !== null && this.authSessionId !== undefined) {
    output.writeFieldBegin('authSessionId', Thrift.Type.STRING, 1);
    output.writeString(this.authSessionId);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var CheckQrCodeVerifiedResponse = module.exports.CheckQrCodeVerifiedResponse = function(args) {
};
CheckQrCodeVerifiedResponse.prototype = {};
CheckQrCodeVerifiedResponse.prototype[Symbol.for("read")] = function(input) {
  input.readStructBegin();
  while (true) {
    var ret = input.readFieldBegin();
    var ftype = ret.ftype;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    input.skip(ftype);
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

CheckQrCodeVerifiedResponse.prototype[Symbol.for("write")] = function(output) {
  output.writeStructBegin('CheckQrCodeVerifiedResponse');
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var CreatePinCodeRequest = module.exports.CreatePinCodeRequest = function(args) {
  this.authSessionId = null;
  if (args) {
    if (args.authSessionId !== undefined && args.authSessionId !== null) {
      this.authSessionId = args.authSessionId;
    }
  }
};
CreatePinCodeRequest.prototype = {};
CreatePinCodeRequest.prototype[Symbol.for("read")] = function(input) {
  input.readStructBegin();
  while (true) {
    var ret = input.readFieldBegin();
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid) {
      case 1:
      if (ftype == Thrift.Type.STRING) {
        this.authSessionId = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

CreatePinCodeRequest.prototype[Symbol.for("write")] = function(output) {
  output.writeStructBegin('CreatePinCodeRequest');
  if (this.authSessionId !== null && this.authSessionId !== undefined) {
    output.writeFieldBegin('authSessionId', Thrift.Type.STRING, 1);
    output.writeString(this.authSessionId);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var CreatePinCodeResponse = module.exports.CreatePinCodeResponse = function(args) {
  this.pinCode = null;
  if (args) {
    if (args.pinCode !== undefined && args.pinCode !== null) {
      this.pinCode = args.pinCode;
    }
  }
};
CreatePinCodeResponse.prototype = {};
CreatePinCodeResponse.prototype[Symbol.for("read")] = function(input) {
  input.readStructBegin();
  while (true) {
    var ret = input.readFieldBegin();
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid) {
      case 1:
      if (ftype == Thrift.Type.STRING) {
        this.pinCode = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

CreatePinCodeResponse.prototype[Symbol.for("write")] = function(output) {
  output.writeStructBegin('CreatePinCodeResponse');
  if (this.pinCode !== null && this.pinCode !== undefined) {
    output.writeFieldBegin('pinCode', Thrift.Type.STRING, 1);
    output.writeString(this.pinCode);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var VerifyCertificateRequest = module.exports.VerifyCertificateRequest = function(args) {
  this.authSessionId = null;
  this.certificate = null;
  if (args) {
    if (args.authSessionId !== undefined && args.authSessionId !== null) {
      this.authSessionId = args.authSessionId;
    }
    if (args.certificate !== undefined && args.certificate !== null) {
      this.certificate = args.certificate;
    }
  }
};
VerifyCertificateRequest.prototype = {};
VerifyCertificateRequest.prototype[Symbol.for("read")] = function(input) {
  input.readStructBegin();
  while (true) {
    var ret = input.readFieldBegin();
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid) {
      case 1:
      if (ftype == Thrift.Type.STRING) {
        this.authSessionId = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.STRING) {
        this.certificate = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

VerifyCertificateRequest.prototype[Symbol.for("write")] = function(output) {
  output.writeStructBegin('VerifyCertificateRequest');
  if (this.authSessionId !== null && this.authSessionId !== undefined) {
    output.writeFieldBegin('authSessionId', Thrift.Type.STRING, 1);
    output.writeString(this.authSessionId);
    output.writeFieldEnd();
  }
  if (this.certificate !== null && this.certificate !== undefined) {
    output.writeFieldBegin('certificate', Thrift.Type.STRING, 2);
    output.writeString(this.certificate);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var VerifyCertificateResponse = module.exports.VerifyCertificateResponse = function(args) {
};
VerifyCertificateResponse.prototype = {};
VerifyCertificateResponse.prototype[Symbol.for("read")] = function(input) {
  input.readStructBegin();
  while (true) {
    var ret = input.readFieldBegin();
    var ftype = ret.ftype;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    input.skip(ftype);
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

VerifyCertificateResponse.prototype[Symbol.for("write")] = function(output) {
  output.writeStructBegin('VerifyCertificateResponse');
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var CheckPinCodeVerifiedRequest = module.exports.CheckPinCodeVerifiedRequest = function(args) {
  this.authSessionId = null;
  if (args) {
    if (args.authSessionId !== undefined && args.authSessionId !== null) {
      this.authSessionId = args.authSessionId;
    }
  }
};
CheckPinCodeVerifiedRequest.prototype = {};
CheckPinCodeVerifiedRequest.prototype[Symbol.for("read")] = function(input) {
  input.readStructBegin();
  while (true) {
    var ret = input.readFieldBegin();
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid) {
      case 1:
      if (ftype == Thrift.Type.STRING) {
        this.authSessionId = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

CheckPinCodeVerifiedRequest.prototype[Symbol.for("write")] = function(output) {
  output.writeStructBegin('CheckPinCodeVerifiedRequest');
  if (this.authSessionId !== null && this.authSessionId !== undefined) {
    output.writeFieldBegin('authSessionId', Thrift.Type.STRING, 1);
    output.writeString(this.authSessionId);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var CheckPinCodeVerifiedResponse = module.exports.CheckPinCodeVerifiedResponse = function(args) {
};
CheckPinCodeVerifiedResponse.prototype = {};
CheckPinCodeVerifiedResponse.prototype[Symbol.for("read")] = function(input) {
  input.readStructBegin();
  while (true) {
    var ret = input.readFieldBegin();
    var ftype = ret.ftype;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    input.skip(ftype);
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

CheckPinCodeVerifiedResponse.prototype[Symbol.for("write")] = function(output) {
  output.writeStructBegin('CheckPinCodeVerifiedResponse');
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var QrCodeLoginV2ForSecureRequest = module.exports.QrCodeLoginV2ForSecureRequest = function(args) {
  this.authSessionId = null;
  this.systemName = null;
  this.modelName = null;
  this.autoLoginIsRequired = null;
  this.nonce = null;
  if (args) {
    if (args.authSessionId !== undefined && args.authSessionId !== null) {
      this.authSessionId = args.authSessionId;
    }
    if (args.systemName !== undefined && args.systemName !== null) {
      this.systemName = args.systemName;
    }
    if (args.modelName !== undefined && args.modelName !== null) {
      this.modelName = args.modelName;
    }
    if (args.autoLoginIsRequired !== undefined && args.autoLoginIsRequired !== null) {
      this.autoLoginIsRequired = args.autoLoginIsRequired;
    }
    if (args.nonce !== undefined && args.nonce !== null) {
      this.nonce = args.nonce;
    }
  }
};
QrCodeLoginV2ForSecureRequest.prototype = {};
QrCodeLoginV2ForSecureRequest.prototype[Symbol.for("read")] = function(input) {
  input.readStructBegin();
  while (true) {
    var ret = input.readFieldBegin();
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid) {
      case 1:
      if (ftype == Thrift.Type.STRING) {
        this.authSessionId = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.STRING) {
        this.systemName = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 3:
      if (ftype == Thrift.Type.STRING) {
        this.modelName = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 4:
      if (ftype == Thrift.Type.BOOL) {
        this.autoLoginIsRequired = input.readBool();
      } else {
        input.skip(ftype);
      }
      break;
      case 5:
      if (ftype == Thrift.Type.STRING) {
        this.nonce = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

QrCodeLoginV2ForSecureRequest.prototype[Symbol.for("write")] = function(output) {
  output.writeStructBegin('QrCodeLoginV2ForSecureRequest');
  if (this.authSessionId !== null && this.authSessionId !== undefined) {
    output.writeFieldBegin('authSessionId', Thrift.Type.STRING, 1);
    output.writeString(this.authSessionId);
    output.writeFieldEnd();
  }
  if (this.systemName !== null && this.systemName !== undefined) {
    output.writeFieldBegin('systemName', Thrift.Type.STRING, 2);
    output.writeString(this.systemName);
    output.writeFieldEnd();
  }
  if (this.modelName !== null && this.modelName !== undefined) {
    output.writeFieldBegin('modelName', Thrift.Type.STRING, 3);
    output.writeString(this.modelName);
    output.writeFieldEnd();
  }
  if (this.autoLoginIsRequired !== null && this.autoLoginIsRequired !== undefined) {
    output.writeFieldBegin('autoLoginIsRequired', Thrift.Type.BOOL, 4);
    output.writeBool(this.autoLoginIsRequired);
    output.writeFieldEnd();
  }
  if (this.nonce !== null && this.nonce !== undefined) {
    output.writeFieldBegin('nonce', Thrift.Type.STRING, 5);
    output.writeString(this.nonce);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var TokenV3IssueResult = module.exports.TokenV3IssueResult = function(args) {
  this.accessToken = null;
  this.refreshToken = null;
  this.durationUntilRefreshInSec = null;
  this.loginSessionId = null;
  this.tokenIssueTimeEpochSec = null;
  if (args) {
    if (args.accessToken !== undefined && args.accessToken !== null) {
      this.accessToken = args.accessToken;
    }
    if (args.refreshToken !== undefined && args.refreshToken !== null) {
      this.refreshToken = args.refreshToken;
    }
    if (args.durationUntilRefreshInSec !== undefined && args.durationUntilRefreshInSec !== null) {
      this.durationUntilRefreshInSec = args.durationUntilRefreshInSec;
    }
    if (args.loginSessionId !== undefined && args.loginSessionId !== null) {
      this.loginSessionId = args.loginSessionId;
    }
    if (args.tokenIssueTimeEpochSec !== undefined && args.tokenIssueTimeEpochSec !== null) {
      this.tokenIssueTimeEpochSec = args.tokenIssueTimeEpochSec;
    }
  }
};
TokenV3IssueResult.prototype = {};
TokenV3IssueResult.prototype[Symbol.for("read")] = function(input) {
  input.readStructBegin();
  while (true) {
    var ret = input.readFieldBegin();
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid) {
      case 1:
      if (ftype == Thrift.Type.STRING) {
        this.accessToken = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.STRING) {
        this.refreshToken = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 3:
      if (ftype == Thrift.Type.I64) {
        this.durationUntilRefreshInSec = input.readI64();
      } else {
        input.skip(ftype);
      }
      break;
      case 5:
      if (ftype == Thrift.Type.STRING) {
        this.loginSessionId = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 6:
      if (ftype == Thrift.Type.I64) {
        this.tokenIssueTimeEpochSec = input.readI64();
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

TokenV3IssueResult.prototype[Symbol.for("write")] = function(output) {
  output.writeStructBegin('TokenV3IssueResult');
  if (this.accessToken !== null && this.accessToken !== undefined) {
    output.writeFieldBegin('accessToken', Thrift.Type.STRING, 1);
    output.writeString(this.accessToken);
    output.writeFieldEnd();
  }
  if (this.refreshToken !== null && this.refreshToken !== undefined) {
    output.writeFieldBegin('refreshToken', Thrift.Type.STRING, 2);
    output.writeString(this.refreshToken);
    output.writeFieldEnd();
  }
  if (this.durationUntilRefreshInSec !== null && this.durationUntilRefreshInSec !== undefined) {
    output.writeFieldBegin('durationUntilRefreshInSec', Thrift.Type.I64, 3);
    output.writeI64(this.durationUntilRefreshInSec);
    output.writeFieldEnd();
  }
  if (this.loginSessionId !== null && this.loginSessionId !== undefined) {
    output.writeFieldBegin('loginSessionId', Thrift.Type.STRING, 5);
    output.writeString(this.loginSessionId);
    output.writeFieldEnd();
  }
  if (this.tokenIssueTimeEpochSec !== null && this.tokenIssueTimeEpochSec !== undefined) {
    output.writeFieldBegin('tokenIssueTimeEpochSec', Thrift.Type.I64, 6);
    output.writeI64(this.tokenIssueTimeEpochSec);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var QrCodeLoginV2Response = module.exports.QrCodeLoginV2Response = function(args) {
  this.certificate = null;
  this.tokenV3IssueResult = null;
  this.mid = null;
  this.lastBindTimestamp = null;
  this.metaData = null;
  if (args) {
    if (args.certificate !== undefined && args.certificate !== null) {
      this.certificate = args.certificate;
    }
    if (args.tokenV3IssueResult !== undefined && args.tokenV3IssueResult !== null) {
      this.tokenV3IssueResult = new ttypes.TokenV3IssueResult(args.tokenV3IssueResult);
    }
    if (args.mid !== undefined && args.mid !== null) {
      this.mid = args.mid;
    }
    if (args.lastBindTimestamp !== undefined && args.lastBindTimestamp !== null) {
      this.lastBindTimestamp = args.lastBindTimestamp;
    }
    if (args.metaData !== undefined && args.metaData !== null) {
      this.metaData = Thrift.copyMap(args.metaData, [null]);
    }
  }
};
QrCodeLoginV2Response.prototype = {};
QrCodeLoginV2Response.prototype[Symbol.for("read")] = function(input) {
  input.readStructBegin();
  while (true) {
    var ret = input.readFieldBegin();
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid) {
      case 1:
      if (ftype == Thrift.Type.STRING) {
        this.certificate = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 3:
      if (ftype == Thrift.Type.STRUCT) {
        this.tokenV3IssueResult = new ttypes.TokenV3IssueResult();
        this.tokenV3IssueResult[Symbol.for("read")](input);
      } else {
        input.skip(ftype);
      }
      break;
      case 4:
      if (ftype == Thrift.Type.STRING) {
        this.mid = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 9:
      if (ftype == Thrift.Type.I64) {
        this.lastBindTimestamp = input.readI64();
      } else {
        input.skip(ftype);
      }
      break;
      case 10:
      if (ftype == Thrift.Type.MAP) {
        this.metaData = {};
        var _rtmp31 = input.readMapBegin();
        var _size0 = _rtmp31.size || 0;
        for (var _i2 = 0; _i2 < _size0; ++_i2) {
          var key3 = null;
          var val4 = null;
          key3 = input.readString();
          val4 = input.readString();
          this.metaData[key3] = val4;
        }
        input.readMapEnd();
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

QrCodeLoginV2Response.prototype[Symbol.for("write")] = function(output) {
  output.writeStructBegin('QrCodeLoginV2Response');
  if (this.certificate !== null && this.certificate !== undefined) {
    output.writeFieldBegin('certificate', Thrift.Type.STRING, 1);
    output.writeString(this.certificate);
    output.writeFieldEnd();
  }
  if (this.tokenV3IssueResult !== null && this.tokenV3IssueResult !== undefined) {
    output.writeFieldBegin('tokenV3IssueResult', Thrift.Type.STRUCT, 3);
    this.tokenV3IssueResult[Symbol.for("write")](output);
    output.writeFieldEnd();
  }
  if (this.mid !== null && this.mid !== undefined) {
    output.writeFieldBegin('mid', Thrift.Type.STRING, 4);
    output.writeString(this.mid);
    output.writeFieldEnd();
  }
  if (this.lastBindTimestamp !== null && this.lastBindTimestamp !== undefined) {
    output.writeFieldBegin('lastBindTimestamp', Thrift.Type.I64, 9);
    output.writeI64(this.lastBindTimestamp);
    output.writeFieldEnd();
  }
  if (this.metaData !== null && this.metaData !== undefined) {
    output.writeFieldBegin('metaData', Thrift.Type.MAP, 10);
    output.writeMapBegin(Thrift.Type.STRING, Thrift.Type.STRING, Thrift.objectLength(this.metaData));
    for (var kiter5 in this.metaData) {
      if (this.metaData.hasOwnProperty(kiter5)) {
        var viter6 = this.metaData[kiter5];
        output.writeString(kiter5);
        output.writeString(viter6);
      }
    }
    output.writeMapEnd();
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

